import { createServer as httpsServer } from 'node:https';
import { createServer as httpServer } from 'node:http';
import { readFile, writeFile, cp } from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import { chromium } from './browser.js';
const body = '通用正文保留中文、代码和段落。'.repeat(1400) + 'ENTRY-DROP-COMPLETE-END';
const fixture = kind => `<!doctype html><html><head><title>${kind} upload fixture</title><style>
html,body{margin:0;font:14px system-ui;color:#222;background:white}main{padding:12px;margin-top:70px}input-area-v2,#dock{display:block;border:1px solid #ddd;border-radius:12px;padding:10px}#files{display:flex;gap:4px;flex-wrap:wrap}.file-preview-container,.file-card{border:1px solid #ddd;border-radius:8px;padding:6px;max-width:100%}.gem-attachment-text,.filename{overflow-wrap:anywhere}gem-attachment{display:inline-flex;align-items:center;gap:6px}.gem-attachment-close-button{visibility:hidden}.file-preview-container:hover .gem-attachment-close-button{visibility:visible}mat-progress-spinner{display:inline-block;width:14px;height:14px;background:#ddd}.ql-editor,textarea{display:block;width:100%;min-height:80px;box-sizing:border-box;white-space:pre-wrap}button{padding:8px}.portal{position:fixed;bottom:140px;z-index:10;background:white;border:1px solid #ddd;padding:10px}
</style></head><body><main>${kind==='gemini'?'<input-area-v2><div id="files"></div><div class="input-area"><rich-textarea><div class="ql-editor" contenteditable="true" role="textbox" aria-label="Prompt"><p><br></p></div></rich-textarea><button id="tools" type="button" aria-label="上传和工具" aria-expanded="false">Tools</button><button id="send" class="send-button" aria-label="发送">Send</button></div></input-area-v2>':kind==='generic'?'<section id="dock" data-dropzone><div id="files"></div><div id="shell"><textarea aria-label="Prompt"></textarea><input type="file" accept=".txt" hidden><button id="tools" type="button" aria-label="Upload files">Files</button><button id="send" type="button" aria-label="Send">Send</button></div></section>':'<form><textarea id="prompt-textarea"></textarea><button aria-label="Send" type="submit">Send</button></form>'}</main><script>
window.fixtureEpoch=crypto.randomUUID();window.sent=[];window.uploads=[];window.removes=[];window.events=[];window.menuClicks=0;window.inputChanges=0;window.entryReads=0;window.mode='pending';window.consumer='entry';window.compatUnavailable=false;window.lateDelay=0;window.ignoreRemoval=false;
const kind=${JSON.stringify(kind)},editor=document.querySelector('.ql-editor,textarea');
window.nativeEntryMethod=DataTransferItem.prototype.webkitGetAsEntry;
const read=()=>editor.tagName==='TEXTAREA'?editor.value:editor.innerText;
const write=text=>{if(editor.tagName==='TEXTAREA')editor.value=text;else editor.innerText=text;editor.dispatchEvent(new InputEvent('input',{bubbles:true}));};
window.addCard=(name,user=false)=>{const outer=document.createElement('div');outer.dataset.name=name;outer.dataset.user=String(user);outer.className=kind==='gemini'?'file-preview-container':'file-card';const card=kind==='gemini'?document.createElement('gem-attachment'):outer;if(card!==outer)outer.append(card);
 const label=document.createElement('span');label.className=kind==='gemini'?'gem-attachment-text':'filename';label.textContent=name;
 const meta=document.createElement('span');meta.className=kind==='gemini'?'gem-attachment-extension-label':'metadata';meta.textContent=user?'TXT':kind==='gemini'?'TXT':'Uploading...';if(kind==='gemini')label.textContent=name.slice(0,-4);
 const close=document.createElement('button');close.type='button';if(kind==='gemini')close.className='gem-attachment-close-button';close.setAttribute('aria-label',(kind==='gemini'?'close ':'Remove ')+name);close.onclick=()=>{removes.push(name);if(!ignoreRemoval||user)outer.remove();};card.append(meta,label,close);
 if(!user){if(kind==='gemini')card.append(document.createElement('mat-progress-spinner'));else outer.dataset.state='uploading';}
 document.querySelector('#files').append(outer);return outer;};
window.complete=()=>{for(const card of document.querySelectorAll('[data-user=false]')){card.querySelector('mat-progress-spinner')?.remove();card.dataset.state='ready';const meta=card.querySelector('.metadata');if(meta)meta.textContent='TXT 34KB';}};
window.fail=()=>{for(const card of document.querySelectorAll('[data-user=false]')){card.querySelector('mat-progress-spinner')?.remove();card.dataset.state='failed';const error=document.createElement('span');error.setAttribute('role','alert');error.textContent='正文文件解析失败：fixture';card.append(error);}};
async function upload(file,transport){uploads.push({name:file.name,type:file.type,size:file.size,text:await file.text(),transport});const append=()=>{addCard(file.name);if(mode==='ready')complete();if(mode==='failed')fail();};if(lateDelay)setTimeout(append,lateDelay);else append();}
window.addEventListener('sider-file-drop-capability',event=>{if(compatUnavailable)event.stopPropagation();},true);
if(kind!=='chatgpt'){
 addCard('user.txt',true);
 for(const type of ['dragenter','dragover','drop'])document.addEventListener(type,event=>{event.preventDefault();events.push({type,name:event.dataTransfer.files[0]?.name,target:event.target===editor,itemsNative:event.dataTransfer.items instanceof DataTransferItemList,itemNative:event.dataTransfer.items[0] instanceof DataTransferItem});if(type!=='drop')return;
  if(consumer==='files'){upload(event.dataTransfer.files[0],'files');return;}
  const items=[...event.dataTransfer.items],entry=items[0].webkitGetAsEntry();entryReads++;if(!entry?.isFile)return;
  entry.file(file=>{if(file!==event.dataTransfer.files[0])throw Error('File identity changed');upload(file,'entry');});});
 document.querySelector('#tools').onclick=()=>{menuClicks++;const menu=document.createElement('div');menu.className='portal';menu.setAttribute('role','menu');const action=document.createElement('button');action.type='button';action.textContent='文件';const input=document.createElement('input');input.type='file';input.hidden=true;input.accept='.txt';input.onchange=()=>{inputChanges++;upload(input.files[0],'input');menu.remove();};action.onclick=()=>input.click();menu.append(action,input);document.body.append(menu);};
 document.querySelector('#send').onclick=event=>{event.preventDefault();sent.push({text:read(),files:[...document.querySelectorAll('[data-name]')].map(card=>card.dataset.name)});for(const card of document.querySelectorAll('[data-user=false]'))card.remove();write('');};
 editor.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.ctrlKey&&!event.altKey&&!event.metaKey){event.preventDefault();document.querySelector('#send').click();}});
}else document.querySelector('form').onsubmit=event=>event.preventDefault();
</script></body></html>`;
const tls=httpsServer({key:await readFile('tests/browser/fixtures/test-key.pem'),cert:await readFile('tests/browser/fixtures/test-cert.pem')},(req,res)=>{const host=req.headers.host||'',kind=host.startsWith('gemini')?'gemini':host.startsWith('arbitrary')?'generic':'chatgpt';res.writeHead(200,{'content-type':'text/html; charset=utf-8','content-security-policy':"frame-ancestors 'none'; script-src 'unsafe-inline'",'x-frame-options':'DENY'});res.end(fixture(kind));});
const source=httpServer((_req,res)=>{res.writeHead(200,{'content-type':'text/html; charset=utf-8'});res.end('<html><title>Shared entry source</title><main><article><h1>正文</h1><p>'+body+'</p></article></main></html>');});
await new Promise(resolve=>tls.listen(0,'127.0.0.1',resolve));await new Promise(resolve=>source.listen(0,'127.0.0.1',resolve));
const productionManifest=JSON.parse(await readFile('manifest.json','utf8')),extension=path.resolve('tmp/browser/entry-drop-extension');assert.ok(extension.startsWith(path.resolve('tmp/browser')+path.sep));await cp('dist',extension,{recursive:true});
const manifest=structuredClone(productionManifest);manifest.host_permissions.push('https://gemini.google.com/*','https://arbitrary-ai.test/*','http://127.0.0.1/*');await writeFile(path.join(extension,'manifest.json'),JSON.stringify(manifest));
const checks=[],errors=[];const passed=message=>{checks.push(message);console.log('PASS '+message);};let context,fileChoosers=0;
try{
 context=await chromium.launchPersistentContext(path.resolve('tmp/browser/entry-drop-profile-'+Date.now()),{...(process.env.SIDER_CHROMIUM ? { executablePath: process.env.SIDER_CHROMIUM } : {}),headless:true,ignoreHTTPSErrors:true,viewport:{width:420,height:840},args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`,'--enable-unsafe-extension-debugging',`--host-resolver-rules=MAP chatgpt.com:443 127.0.0.1:${tls.address().port},MAP gemini.google.com:443 127.0.0.1:${tls.address().port},MAP arbitrary-ai.test:443 127.0.0.1:${tls.address().port}`,'--no-proxy-server','--ignore-certificate-errors']});
 const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker'),id=new URL(worker.url()).hostname;
 const article=await context.newPage(),sourceURL=`http://127.0.0.1:${source.address().port}/article`;await article.goto(sourceURL);const tab=await worker.evaluate(async url=>(await chrome.tabs.query({})).find(tab=>tab.url===url),sourceURL);
 const panel=await context.newPage();panel.on('pageerror',error=>errors.push(error.message));panel.on('filechooser',chooser=>{fileChoosers++;chooser.setFiles([]).catch(()=>{});});await panel.goto(`chrome-extension://${id}/panel.html?sourceTab=${tab.id}`);
 const chat=panel.frameLocator('iframe'),message=data=>panel.evaluate(data=>chrome.runtime.sendMessage(data),data),native=fn=>chat.locator('body').evaluate(fn),editor=()=>chat.locator('.ql-editor,textarea'),status=()=>chat.locator('.status');
 const state=()=>native(()=>({sent,uploads,removes,events,menuClicks,inputChanges,entryReads,prototypeUnchanged:nativeEntryMethod===DataTransferItem.prototype.webkitGetAsEntry,markerRemoved:!document.querySelector('.ql-editor,textarea').hasAttribute('data-sider-file-drop')}));
 const wait=async(expression,arg)=>chat.locator('body').evaluate((_body,{expression,arg})=>new Promise((resolve,reject)=>{const fn=new Function('arg','return ('+expression+');'),start=Date.now(),timer=setInterval(()=>{try{if(fn(arg)){clearInterval(timer);resolve();}else if(Date.now()-start>7000)throw new Error(expression);}catch(error){clearInterval(timer);reject(error);}},20);}),{expression,arg});
 await chat.locator('#sider-enhancement').waitFor();assert.equal((await message({type:'SIDER_AI_WEB_SETTINGS_SAVE',settings:{activeSiteId:'gemini',customSites:[]}})).ok,true);
 assert.equal((await message({type:'SIDER_CONTEXT_SETTINGS_PATCH',tabId:tab.id,patch:{pageMode:'auto',pageThreshold:10000}})).ok,true);
 const reset=async()=>{const previous=await native(()=>fixtureEpoch),navigation=panel.waitForEvent('framenavigated',{predicate:frame=>/^https:\/\/(gemini.google.com|arbitrary-ai.test)\//.test(frame.url())});await panel.locator('#reload-chatgpt').click();await navigation;await chat.locator('#sider-enhancement').waitFor();assert.notEqual(await native(()=>fixtureEpoch),previous);await message({type:'SIDER_TAB_ATTACHMENT_SET',tabId:tab.id,kind:'url',enabled:true});await message({type:'SIDER_TAB_ATTACHMENT_SET',tabId:tab.id,kind:'page',enabled:true});await chat.locator('[data-chip="page"]').waitFor();await editor().fill('待发送的原问题');};
 const pending=async()=>{await editor().press('Enter');await wait('uploads.length===1');await status().filter({hasText:'正在准备正文附件'}).waitFor();};
 await reset();await pending();let s=await state();assert.equal(s.uploads[0].transport,'entry');assert.equal(s.menuClicks,0);assert.equal(s.inputChanges,0);assert.equal(s.events.filter(e=>e.type==='drop').length,1);assert.ok(s.events.every(e=>e.target&&e.itemsNative&&e.itemNative));assert.ok(s.uploads[0].text.includes(body));assert.ok(s.uploads[0].text.includes(sourceURL));assert.equal(s.uploads[0].size,Buffer.byteLength(s.uploads[0].text));assert.equal(s.prototypeUnchanged,true);assert.equal(s.markerRemoved,true);passed('Gemini MAIN entry consumer reads the full UTF-8 file from one ISOLATED drop, without opening the menu or altering native prototypes');
 await editor().press('Enter');await editor().press('Enter');await native(()=>new Promise(resolve=>setTimeout(resolve,6600)));s=await state();assert.equal(s.uploads.length,1);assert.equal(s.sent.length,0);assert.equal(await editor().innerText(),'待发送的原问题');await native(()=>complete());await wait('sent.length===1');s=await state();assert.ok(s.sent[0].text.includes(s.uploads[0].name));assert.equal(s.events.filter(e=>e.type==='drop').length,1);passed('pending entry uploads wait beyond 6.5 seconds and repeated Enter resumes exactly one send when the native tile is ready');
 await chat.locator('[data-chip="page"]').waitFor({state:'hidden'});await message({type:'SIDER_TAB_ATTACHMENT_SET',tabId:tab.id,kind:'page',enabled:true});await chat.locator('[data-chip="page"]').waitFor();
 await editor().fill('保留下一条问题');await editor().press('Enter');await wait('uploads.length===2');await chat.locator('[data-chip="page"] button').click();await wait('document.querySelectorAll("[data-user=false]").length===0');assert.equal(await chat.locator('[data-user=true]').count(),1);assert.equal(await editor().innerText(),'保留下一条问题');passed('after native consumption, explicitly reselecting then cancelling the next owned upload preserves the user attachment and draft');
 await reset();await native(()=>{mode='failed';});await editor().press('Enter');await status().filter({hasText:'fixture'}).waitFor();s=await state();assert.equal(s.uploads.length,1);assert.equal(s.sent.length,0);assert.equal(s.menuClicks,0);assert.equal(s.removes.length,1);assert.equal(await editor().innerText(),'待发送的原问题');passed('a failed entry upload preserves the question and never retries through the menu');
 await reset();await pending();await chat.locator('[data-chip="page"] button').click();await wait('removes.length===1');s=await state();assert.equal(s.sent.length,0);assert.equal(s.uploads.length,1);assert.equal(s.menuClicks,0);assert.equal(await chat.locator('[data-user=true]').count(),1);passed('reference cancellation during entry upload cleans only the owned attachment and prevents send');
 await reset();await native(()=>{lateDelay=700;});await editor().press('Enter');await wait('uploads.length===1');await editor().fill('修改后的问题');await wait('removes.length===1');s=await state();assert.equal(s.sent.length,0);assert.equal(s.uploads.length,1);assert.equal(await editor().innerText(),'修改后的问题');passed('late entry cards are cleaned after a draft change without sending the obsolete question');
 await reset();await native(()=>{consumer='files';mode='ready';});await chat.locator('#send').click();await wait('sent.length===1');s=await state();assert.equal(s.uploads[0].transport,'files');assert.equal(s.menuClicks,0);assert.ok(s.uploads[0].text.includes(body));passed('the same transfer also works for FileList consumers through one native send-button click');
 await reset();await native(()=>{compatUnavailable=true;mode='ready';});await editor().press('Enter');await wait('sent.length===1');s=await state();assert.equal(s.uploads[0].transport,'input');assert.equal(s.menuClicks,1);assert.equal(s.events.length,0);passed('missing drop compatibility is detected before dispatch and selects the existing semantic file-action route once');
 const custom={id:'custom-entry-fixture-0001',name:'Entry AI',url:'https://arbitrary-ai.test/',selectors:{}};
 assert.equal((await message({type:'SIDER_AI_WEB_SETTINGS_SAVE',settings:{activeSiteId:custom.id,customSites:[custom]}})).ok,true);
 await reset();await pending();s=await state();assert.equal(s.uploads[0].transport,'entry');assert.equal(s.menuClicks,0);assert.ok(s.uploads[0].text.includes(body));assert.equal(s.prototypeUnchanged,true);await native(()=>complete());await wait('sent.length===1');passed('an arbitrary configured AI origin uses the same entry-compatible drop in its explicit dropzone ahead of its upload menu');
 await reset();await native(()=>{consumer='files';mode='ready';});await editor().press('Enter');await wait('sent.length===1');s=await state();assert.equal(s.uploads[0].transport,'files');assert.equal(s.menuClicks,0);assert.equal(s.inputChanges,0);passed('arbitrary FileList consumers retain the single-drop behavior without input change events');
 await reset();await panel.setViewportSize({width:320,height:740});await pending();const layout=await native(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(layout.scroll<=layout.width+1);await panel.screenshot({path:'tmp/browser/entry-drop-320.png'});await chat.locator('[data-chip="page"] button').click();await wait('removes.length===1');passed('entry attachment preview and pending progress fit a 320px sidebar');
 const registrations=await worker.evaluate(()=>chrome.scripting.getRegisteredContentScripts());for(const origin of ['https://gemini.google.com','https://arbitrary-ai.test']){assert.ok(registrations.some(script=>script.matches[0]===origin+'/*'&&script.world==='MAIN'&&script.runAt==='document_start'&&script.js.includes('file-drop-main.js')));assert.ok(registrations.some(script=>script.matches[0]===origin+'/*'&&script.world==='ISOLATED'&&script.js.includes('ai-content.js')));}assert.equal(fileChoosers,0);assert.deepEqual(errors,[]);assert.deepEqual(JSON.parse(await readFile('manifest.json','utf8')),productionManifest);passed('authorized dynamic origins register the shared MAIN helper and ISOLATED enhancement, with no picker windows or page errors');
 await writeFile('tmp/browser/entry-drop-results.json',JSON.stringify({version:productionManifest.version,checks,errors,fileChoosers,browser:await context.browser().version(),bodyChars:body.length,fixtureOnly:true},null,2));console.log(JSON.stringify({passed:checks.length,errors}));
}catch(error){
 for(const page of context?.pages()||[]){
  if(!page.url().startsWith('chrome-extension:'))continue;
  for(const frame of page.frames().slice(1)){
   console.log('DEBUG '+(await frame.locator('body').innerText().catch(()=>'' )).slice(0,2000));
   const statuses=await frame.locator('.status').evaluateAll(nodes=>nodes.map(n=>({text:n.textContent,hidden:n.hidden}))).catch(()=>[]);
   console.log('STATUS '+JSON.stringify(statuses));
   const state=await frame.evaluate(()=>({mode,uploads:uploads.map(({name,size,transport})=>({name,size,transport})),events,removes,sent:sent.length})).catch(()=>({}));
   console.log('STATE '+JSON.stringify(state));
  }
 }
 throw error;
}
finally{await context?.close();await new Promise(resolve=>tls.close(resolve));await new Promise(resolve=>source.close(resolve));}
