import { createServer as httpsServer } from 'node:https';
import { createServer as httpServer } from 'node:http';
import { readFile, writeFile, cp } from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import { chromium } from './browser.js';
const body='Gemini 引用正文，保留完整中文和段落。'.repeat(1500)+'GEMINI-COMPLETE-BODY-END';
const fixture=gemini=>`<!doctype html><html><head><title>Native upload fixture</title><style>
html,body{margin:0;font:14px system-ui;background:#fff;color:#222}main{padding:12px;margin-top:80px}input-area-v2{display:block;border:1px solid #ddd;border-radius:12px;padding:10px}.input-area{padding:8px}.ql-editor,textarea{min-height:80px;box-sizing:border-box;width:100%;display:block;border:1px solid #ccc;white-space:pre-wrap}button{padding:8px}#files{display:flex;gap:4px;flex-wrap:wrap}.file-preview-container{max-width:100%;border:1px solid #ddd;border-radius:8px;padding:6px}gem-attachment{display:inline-flex;align-items:center;gap:6px}.gem-attachment-text{overflow-wrap:anywhere}.gem-attachment-close-button{visibility:hidden}.file-preview-container:hover .gem-attachment-close-button{visibility:visible}mat-progress-spinner{display:inline-block;width:14px;height:14px;background:#ddd}.portal{position:fixed;bottom:180px;border:1px solid #ddd;background:white;padding:10px;z-index:10}images-files-uploader{display:block}
</style></head><body><main>${gemini?'<input-area-v2><div id="files"></div><div class="input-area"><rich-textarea><div class="ql-editor" contenteditable="true" role="textbox" aria-label="Prompt"><p><br></p></div></rich-textarea><button id="tools" type="button" aria-label="上传和工具" aria-expanded="false">Tools</button><button id="send" class="send-button" aria-label="发送">Send</button></div></input-area-v2>':'<form><textarea id="prompt-textarea"></textarea><button aria-label="Send" type="submit">Send</button></form>'}</main><script>
window.sent=[];window.uploads=[];window.removes=[];window.drops=0;window.menuClicks=0;window.menuDelay=100;window.mode='pending';window.ignoreRemoval=false;window.staleSelections=0;window.ambiguous=false;window.nativeActionClicks=0;window.pickerRequests=0;window.pickerCancelled=0;window.pickerMode='retained';window.actionChange=false;
// Exercise the semantic menu route explicitly; entry-drop.mjs covers MAIN drop.
window.addEventListener('sider-file-drop-capability',event=>event.stopPropagation(),true);
const gemini=${gemini};const editor=document.querySelector('.ql-editor,textarea');const read=()=>gemini?editor.innerText:editor.value;
const write=text=>{if(gemini)editor.innerText=text;else editor.value=text;editor.dispatchEvent(new InputEvent('input',{bubbles:true}));};
if(gemini){
 const area=document.querySelector('#files'),send=document.querySelector('#send'),trigger=document.querySelector('#tools');
 const staleInput=parent=>{const input=document.createElement('input');input.type='file';input.accept='.txt,.pdf';input.hidden=true;input.onchange=()=>staleSelections++;parent.append(input);return input;};
 for(const mode of ['outside','hidden-menu','old-open-menu']){const root=document.createElement('div');root.className='stale-uploader';if(mode!=='outside')root.setAttribute('role','menu');if(mode==='old-open-menu'){root.style.position='absolute';root.style.left='12px';root.style.top='4px';}else root.hidden=true;const local=document.createElement('images-files-uploader'),action=document.createElement('button');action.type='button';action.setAttribute('role','menuitem');action.setAttribute('aria-label','Upload files');action.textContent='Other upload';local.append(action);staleInput(local);root.append(local);document.body.append(root);}
 const update=()=>send.disabled=!read().trim()||Boolean(area.querySelector('mat-progress-spinner'));
 editor.addEventListener('input',update);document.addEventListener('drop',event=>{event.preventDefault();drops++;});
 function card(name,user=false){const outer=document.createElement('div');outer.className='file-preview-container';outer.dataset.user=String(user);outer.dataset.name=name;
 const tooltip=document.createElement('div');tooltip.id='filename-'+Math.random().toString(16).slice(2);tooltip.setAttribute('role','tooltip');tooltip.hidden=true;tooltip.textContent=name;document.body.append(tooltip);outer.setAttribute('aria-describedby',tooltip.id);
 const tile=document.createElement('gem-attachment');tile.tabIndex=0;const type=document.createElement('span');type.className='gem-attachment-extension-label';type.textContent='TXT';
 const label=document.createElement('span');label.className='gem-attachment-text';label.textContent=name.slice(0,10)+'...'+name.slice(-12,-4);const close=document.createElement('button');close.type='button';close.className='gem-attachment-close-button';close.setAttribute('aria-label','close '+label.textContent);
 close.onclick=()=>{removes.push(name);if(!ignoreRemoval||user){outer.remove();tooltip.remove();update();}};tile.append(type,label,close);outer.append(tile);area.append(outer);
 if(!user){const spinner=document.createElement('mat-progress-spinner');tile.append(spinner);}update();return outer;}
 window.complete=()=>{for(const el of area.querySelectorAll('[data-user=false]'))el.querySelector('mat-progress-spinner')?.remove();update();};
 window.fail=reason=>{for(const el of area.querySelectorAll('[data-user=false]')){el.querySelector('mat-progress-spinner')?.remove();el.querySelector('.gem-attachment-extension-label')?.remove();const icon=document.createElement('mat-icon');icon.setAttribute('data-mat-icon-name','error_outline');icon.setAttribute('aria-hidden','true');icon.title=reason;icon.textContent='!';el.querySelector('gem-attachment').append(icon);}update();};
 card('user.txt',true);
 async function upload(file){const data={name:file.name,size:file.size,type:file.type,text:await file.text()};uploads.push(data);card(file.name);if(mode==='ready')complete();if(mode==='failed')fail('Gemini native fixture failure');}
 trigger.onclick=()=>{if(trigger.getAttribute('aria-expanded')==='true'){trigger.setAttribute('aria-expanded','false');document.querySelector('.portal')?.remove();return;}trigger.setAttribute('aria-expanded','true');menuClicks++;
 setTimeout(()=>{if(trigger.getAttribute('aria-expanded')!=='true')return;const menu=document.createElement('div');menu.id='current-upload-menu';menu.className='portal';menu.setAttribute('role','menu');const local=document.createElement('images-files-uploader'),inner=document.createElement('div');inner.setAttribute('role','menu');inner.append(local);menu.append(inner);
 const action=document.createElement('button');action.type='button';action.setAttribute('role','menuitem');action.setAttribute('aria-label','上传文件. 文档、数据、代码文件');action.textContent='Upload files';local.append(action);
 const nativePicker=()=>{const input=document.createElement('input');input.type='file';input.setAttribute('aria-hidden','true');input.style.display='none';input.onclick=event=>{pickerRequests++;if(event.defaultPrevented)pickerCancelled++;};input.onchange=()=>{const file=input.files[0];menu.remove();trigger.setAttribute('aria-expanded','false');upload(file);input.value='';};local.append(input);return input;};
 const retained=nativePicker();staleInput(local);
 action.onclick=()=>{nativeActionClicks++;if(pickerMode==='none')return;const input=pickerMode==='dynamic'?nativePicker():retained;input.click();if(pickerMode==='multiple')nativePicker().click();if(actionChange)write('原生上传动作期间修改后的问题');};
 for(const mode of ['hidden','display','aria','inert']){const copy=document.createElement('images-files-uploader');if(mode==='hidden')copy.hidden=true;if(mode==='display')copy.style.display='none';if(mode==='aria')copy.setAttribute('aria-hidden','true');if(mode==='inert')copy.inert=true;staleInput(copy);menu.append(copy);}
 const images=document.createElement('images-files-uploader'),imageAction=document.createElement('button');imageAction.type='button';imageAction.setAttribute('role','menuitem');imageAction.setAttribute('aria-label',ambiguous?'Upload files':'Upload photos');imageAction.textContent='Other files';images.append(imageAction);staleInput(images);menu.append(images);
 for(const [parent,accept] of [[local,'.txt,.pdf'],[menu,'.txt,.doc'],[menu,'image/*']])staleInput(parent).accept=accept;document.body.append(menu);},menuDelay);};
 send.onclick=event=>{event.preventDefault();if(send.disabled)return;sent.push({text:read(),files:[...area.querySelectorAll('.file-preview-container')].map(el=>el.dataset.name),uploads:uploads.map(data=>({...data}))});for(const card of area.querySelectorAll('[data-user=false]'))card.remove();write('');};
 editor.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.ctrlKey&&!event.metaKey&&!event.altKey&&!event.isComposing){event.preventDefault();send.click();}});update();
}else document.querySelector('form').onsubmit=event=>event.preventDefault();
</script></body></html>`;
const tls=httpsServer({key:await readFile('tests/browser/fixtures/test-key.pem'),cert:await readFile('tests/browser/fixtures/test-cert.pem')},(req,res)=>{res.writeHead(200,{'content-type':'text/html; charset=utf-8','content-security-policy':"frame-ancestors 'none'; script-src 'unsafe-inline'",'x-frame-options':'DENY'});res.end(fixture((req.headers.host||'').startsWith('gemini')));});
const source=httpServer((_req,res)=>{res.writeHead(200,{'content-type':'text/html; charset=utf-8'});res.end(`<html><title>Gemini source fixture</title><main><article><h1>Gemini 正文</h1><p>${body}</p></article></main></html>`);});
await new Promise(resolve=>tls.listen(0,'127.0.0.1',resolve));await new Promise(resolve=>source.listen(0,'127.0.0.1',resolve));
const productionManifest=JSON.parse(await readFile('manifest.json','utf8')),extension=path.resolve('tmp/browser/gemini-upload-extension');assert.ok(extension.startsWith(path.resolve('tmp/browser')+path.sep));await cp('dist',extension,{recursive:true});
const manifest=structuredClone(productionManifest);manifest.host_permissions.push('https://gemini.google.com/*','http://127.0.0.1/*');await writeFile(path.join(extension,'manifest.json'),JSON.stringify(manifest));
const checks=[],errors=[],passed=message=>{checks.push(message);console.log('PASS '+message);};let context;let fileChoosers=0;
try{
 context=await chromium.launchPersistentContext(path.resolve('tmp/browser/gemini-upload-profile-'+Date.now()),{...(process.env.SIDER_CHROMIUM ? { executablePath: process.env.SIDER_CHROMIUM } : {}),headless:true,ignoreHTTPSErrors:true,viewport:{width:420,height:840},args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`,'--enable-unsafe-extension-debugging',`--host-resolver-rules=MAP chatgpt.com:443 127.0.0.1:${tls.address().port},MAP gemini.google.com:443 127.0.0.1:${tls.address().port}`,'--no-proxy-server','--ignore-certificate-errors']});
 const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker'),id=new URL(worker.url()).hostname;
 const article=await context.newPage(),sourceURL=`http://127.0.0.1:${source.address().port}/article`;await article.goto(sourceURL);const tab=await worker.evaluate(async url=>(await chrome.tabs.query({})).find(tab=>tab.url===url),sourceURL);
 const panel=await context.newPage();panel.on('pageerror',error=>errors.push(error.message));panel.on('filechooser',chooser=>{fileChoosers++;chooser.setFiles([]).catch(()=>{});});await panel.goto(`chrome-extension://${id}/panel.html?sourceTab=${tab.id}`);
 const chat=panel.frameLocator('iframe'),message=data=>panel.evaluate(data=>chrome.runtime.sendMessage(data),data),native=fn=>chat.locator('body').evaluate(fn),editor=()=>chat.locator('.ql-editor'),status=()=>chat.locator('.status');
 const state=()=>native(()=>({sent,uploads,removes,drops,menuClicks,staleSelections,nativeActionClicks,pickerRequests,pickerCancelled}));
 const wait=async(expression,arg)=>chat.locator('body').evaluate((_body,{expression,arg})=>new Promise((resolve,reject)=>{const fn=new Function('arg','return ('+expression+');'),start=Date.now(),timer=setInterval(()=>{try{if(fn(arg)){clearInterval(timer);resolve();}else if(Date.now()-start>6000)throw new Error(expression);}catch(error){clearInterval(timer);reject(error);}},20);}),{expression,arg});
 await chat.locator('#sider-enhancement').waitFor();assert.equal((await message({type:'SIDER_AI_WEB_SETTINGS_SAVE',settings:{activeSiteId:'gemini',customSites:[]}})).ok,true);
 assert.equal((await message({type:'SIDER_CONTEXT_SETTINGS_PATCH',tabId:tab.id,patch:{pageMode:'auto',pageThreshold:10000}})).ok,true);
 const reset=async()=>{await panel.locator('#reload-chatgpt').click();await chat.locator('#sider-enhancement').waitFor();await panel.getByText('Gemini · 网页引用已就绪',{exact:true}).waitFor();await message({type:'SIDER_TAB_ATTACHMENT_SET',tabId:tab.id,kind:'url',enabled:true});await message({type:'SIDER_TAB_ATTACHMENT_SET',tabId:tab.id,kind:'page',enabled:true});await chat.locator('[data-chip="page"]').waitFor();await editor().fill('待发送的原问题');};
 const pending=async()=>{await editor().press('Enter');await wait('uploads.length===1');await status().filter({hasText:'正在准备正文附件'}).waitFor();};
 await reset();assert.equal(await chat.locator('.input-area input[type=file]').count(),0);assert.equal(await chat.locator('[data-chip="page"] .excerpt').innerText(),'网页正文 · 附件');await pending();let s=await state();assert.equal(s.menuClicks,1);assert.equal(s.uploads.length,1);assert.equal(s.nativeActionClicks,1);assert.equal(s.pickerRequests,1);assert.equal(s.pickerCancelled,1);assert.equal(s.drops,0);assert.equal(s.staleSelections,0);assert.ok(s.uploads[0].text.includes(body));assert.ok(s.uploads[0].text.includes(sourceURL));assert.equal(s.uploads[0].size,Buffer.byteLength(s.uploads[0].text));assert.equal(s.sent.length,0);passed('native action selects its actual retained picker among three local TXT inputs, cancels the picker window and uploads the complete UTF-8 body once');
 assert.equal(await native(()=>[...document.querySelectorAll('.stale-uploader input[type=file]')].every(input=>!input.files.length)),true);passed('out-of-menu and inactive uploader copies are never assigned files and no hidden native input is mistaken for an inactive uploader');
 await editor().press('Enter');await editor().press('Enter');await native(()=>new Promise(resolve=>setTimeout(resolve,6900)));s=await state();assert.equal(s.menuClicks,1);assert.equal(s.uploads.length,1);assert.equal(s.sent.length,0);assert.equal(await status().getAttribute('hidden'),null);assert.ok((await status().innerText()).includes('正在准备正文附件'));assert.equal(await editor().innerText(),'待发送的原问题');passed('upload progress persists beyond 6.5 seconds and repeated Enter preserves the draft without a second upload');
 await native(()=>complete());await wait('sent.length===1');s=await state();assert.ok(s.sent[0].text.includes('待发送的原问题'));assert.ok(s.sent[0].text.includes(s.uploads[0].name));assert.ok(s.sent[0].text.includes(sourceURL));assert.ok(!s.sent[0].text.includes(body));assert.equal(s.sent[0].uploads[0].text,s.uploads[0].text);await status().filter({hasText:/正在准备正文附件|正在取消正文附件/}).waitFor({state:'hidden',timeout:6000});passed('a TXT tile with abbreviated labels, full filename tooltip and a hover-hidden close button resumes exactly one native send and clears progress');
 await chat.locator('[data-chip="page"]').waitFor({state:'hidden'});await message({type:'SIDER_TAB_ATTACHMENT_SET',tabId:tab.id,kind:'page',enabled:true});await chat.locator('[data-chip="page"]').waitFor();
 await editor().fill('清理时保留的问题');await editor().press('Enter');await wait('uploads.length===2');await chat.locator('[data-chip="page"] button').click();await wait('document.querySelectorAll("[data-user=false]").length===0');assert.equal(await chat.locator('[data-user=true]').count(),1);assert.equal(await editor().innerText(),'清理时保留的问题');passed('owned hover-hidden close control cancels the next explicitly selected upload after native consumption while retaining a user TXT and draft');
 await reset();await pending();await native(()=>fail('原站拒绝 TXT：fixture 原因'));await status().filter({hasText:'fixture 原因'}).waitFor();s=await state();assert.equal(s.sent.length,0);assert.equal(s.uploads.length,1);assert.equal(s.removes.length,1);assert.equal(s.drops,0);assert.equal(await editor().innerText(),'待发送的原问题');assert.equal(await chat.locator('[data-chip="page"]').count(),1);assert.equal(await chat.locator('[data-user=true]').count(),1);passed('native error without a TXT type label reports its reason, stops send and cleans only the owned file without text fallback');
 await reset();await pending();await chat.locator('[data-chip="page"] button').click();await wait('removes.length===1');s=await state();assert.equal(s.sent.length,0);assert.equal(s.uploads.length,1);assert.equal(await editor().innerText(),'待发送的原问题');assert.equal(await chat.locator('[data-user=true]').count(),1);passed('cancel during upload prevents native replay and confirms owned cleanup once');
 await reset();await native(()=>{menuDelay=400;});await editor().press('Enter');await wait('menuClicks===1');await editor().press('Enter');await editor().fill('菜单初始化期间修改后的问题');await wait('document.querySelector("#tools").getAttribute("aria-expanded")==="false"');await native(()=>new Promise(resolve=>setTimeout(resolve,450)));s=await state();assert.equal(s.uploads.length,0);assert.equal(s.sent.length,0);assert.equal(s.menuClicks,1);assert.equal(await editor().innerText(),'菜单初始化期间修改后的问题');passed('editing the draft while the native upload menu opens cancels before file dispatch and preserves the new text');
 await reset();await native(()=>{menuDelay=400;});await editor().press('Enter');await wait('menuClicks===1');await chat.locator('[data-chip="page"] button').click();await wait('document.querySelector("#tools").getAttribute("aria-expanded")==="false"');await native(()=>new Promise(resolve=>setTimeout(resolve,450)));assert.equal((await state()).uploads.length,0);assert.equal((await state()).sent.length,0);assert.equal(await editor().innerText(),'待发送的原问题');passed('reference cancellation during lazy menu preparation dispatches no file or message');
 await reset();await pending();await native(()=>{ignoreRemoval=true;});await chat.locator('[data-chip="page"] button').click();await status().filter({hasText:'取消正文附件超时'}).waitFor();await editor().press('Enter');await status().filter({hasText:'取消正文附件超时'}).waitFor();s=await state();assert.equal(s.removes.length,1);assert.equal(s.uploads.length,1);assert.equal(s.sent.length,0);await native(()=>{document.querySelector('[data-user=false]').remove();ignoreRemoval=false;mode='ready';complete();});await message({type:'SIDER_TAB_ATTACHMENT_SET',tabId:tab.id,kind:'page',enabled:true});await chat.locator('[data-chip="page"]').waitFor();await editor().press('Enter');await wait('sent.length===1');assert.equal((await state()).uploads.length,2);assert.equal(await chat.locator('[data-user=true]').count(),1);passed('failed cleanup blocks further uploads; confirmed manual removal and reactive control update allow one explicit retry');
 await reset();await native(()=>{mode='ready';});await editor().press('Shift+Enter');assert.equal((await state()).uploads.length,0);await editor().fill('按钮发送的问题');await chat.locator('#send').click();await wait('sent.length===1');assert.equal((await state()).uploads.length,1);passed('Shift+Enter remains newline input while one real send-button click prepares and sends the attachment');
 await reset();await native(()=>{document.querySelector('#tools').setAttribute('aria-controls','current-upload-menu');mode='ready';});await chat.locator('#tools').click();await chat.locator('#current-upload-menu').waitFor();assert.ok(await chat.locator('images-files-uploader input[type=file]').count()>5);await editor().press('Enter');await wait('sent.length===1');s=await state();assert.equal(s.menuClicks,1);assert.equal(s.uploads.length,1);assert.equal(s.staleSelections,0);passed('an already open ARIA-bound upload menu is reused once while other visible TXT upload menus remain untouched');
 await reset();await native(()=>{ambiguous=true;});await editor().press('Enter');await status().filter({hasText:'Gemini 本地文件上传操作存在多个匹配'}).waitFor();s=await state();assert.equal(s.uploads.length,0);assert.equal(s.sent.length,0);assert.equal(s.staleSelections,0);assert.equal(s.nativeActionClicks,0);assert.equal(await editor().innerText(),'待发送的原问题');assert.equal(await chat.locator('[data-chip="page"]').count(),1);passed('two equally labelled current file-upload actions remain genuinely ambiguous and preserve the question without activating either action');
 await reset();await native(()=>{pickerMode='dynamic';mode='ready';});await editor().press('Enter');await wait('sent.length===1');s=await state();assert.equal(s.nativeActionClicks,1);assert.equal(s.pickerRequests,1);assert.equal(s.pickerCancelled,1);assert.equal(s.uploads.length,1);assert.equal(s.staleSelections,0);assert.ok(s.uploads[0].text.includes(body));passed('a native action-created input is captured across MAIN and ISOLATED worlds and one Enter completes upload and send');
 await reset();await native(()=>{pickerMode='multiple';});await editor().press('Enter');await status().filter({hasText:'调用了多个文件入口'}).waitFor();s=await state();assert.equal(s.nativeActionClicks,1);assert.equal(s.pickerRequests,2);assert.equal(s.pickerCancelled,2);assert.equal(s.uploads.length,0);assert.equal(s.sent.length,0);assert.equal(await editor().innerText(),'待发送的原问题');assert.equal(await chat.locator('[data-chip="page"]').count(),1);passed('an action invoking two distinct inputs cancels both picker activations and dispatches no file or text fallback');
 await reset();await native(()=>{pickerMode='none';});await editor().press('Enter');await status().filter({hasText:'没有提供可确认的 TXT 文件入口'}).waitFor();s=await state();assert.equal(s.nativeActionClicks,1);assert.equal(s.uploads.length,0);assert.equal(s.sent.length,0);assert.equal(await editor().innerText(),'待发送的原问题');passed('an unconfirmed action stops immediately without a phantom upload or cleanup timeout');
 await reset();await native(()=>{actionChange=true;});await editor().press('Enter');await wait('nativeActionClicks===1');await status().filter({hasText:'问题或会话已修改'}).waitFor();s=await state();assert.equal(s.pickerCancelled,1);assert.equal(s.uploads.length,0);assert.equal(s.sent.length,0);assert.equal(await editor().innerText(),'原生上传动作期间修改后的问题');passed('a draft change inside the native upload action cancels before file assignment and preserves the new question');
 await reset();await panel.setViewportSize({width:320,height:740});await pending();const layout=await native(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(layout.scroll<=layout.width+1);await panel.screenshot({path:'tmp/browser/gemini-upload-320.png'});await chat.locator('[data-chip="page"] button').click();await wait('removes.length===1');passed('Gemini preview, persistent progress and reference bar fit a 320px sidebar');
 await reset();await native(()=>{mode='ready';});await editor().fill('');assert.equal(await native(()=>document.querySelector('#send').disabled),true);
 await chat.getByRole('button',{name:'预设',exact:true}).click();await chat.getByRole('button',{name:'新增预设',exact:true}).click();
 await chat.locator('#template-name').fill('空草稿附件');await chat.locator('#template-text').fill('{{content}}');await chat.locator('#template-action').selectOption('send');
 await chat.locator('summary').filter({hasText:'高级'}).click();await chat.locator('#template-delivery').selectOption('file');await chat.getByRole('button',{name:'保存预设',exact:true}).click();
 await chat.getByRole('button',{name:'空草稿附件 · 直接发送',exact:true}).waitFor();await chat.getByRole('button',{name:'关闭',exact:true}).click();
 await chat.getByRole('button',{name:'预设',exact:true}).click();await chat.getByRole('button',{name:'空草稿附件 · 直接发送',exact:true}).click();await wait('sent.length===1');s=await state();
 assert.equal(s.uploads.length,2);for(const file of s.uploads){assert.ok(file.text.includes(body));assert.ok(s.sent[0].text.includes(file.name));}assert.equal(s.sent[0].text.includes(body),false);
 passed('empty-draft direct send uploads two complete files before writing their notes, then enables the native sender and sends once');
 await chat.getByRole('button',{name:'预设',exact:true}).click();await chat.getByRole('button',{name:'编辑预设 空草稿附件',exact:true}).click();await chat.locator('#template-action').selectOption('append');await chat.getByRole('button',{name:'保存预设',exact:true}).click();
 await chat.getByRole('button',{name:'空草稿附件 · 追加',exact:true}).waitFor();await chat.getByRole('button',{name:'关闭',exact:true}).click();await editor().fill('');
 await chat.getByRole('button',{name:'预设',exact:true}).click();await chat.getByRole('button',{name:'空草稿附件 · 追加',exact:true}).click();await status().filter({hasText:'已追加'}).waitFor();s=await state();
 assert.equal(s.uploads.length,3);assert.equal(s.sent.length,1);assert.ok((await editor().innerText()).includes(s.uploads[2].name));assert.equal(await chat.locator('[data-user=true]').count(),1);
 passed('empty-draft fill confirms the native file before inserting its note, preserves the user file, and does not send');
 assert.equal(fileChoosers,0);assert.deepEqual(errors,[]);assert.deepEqual(JSON.parse(await readFile('manifest.json','utf8')),productionManifest);passed('all native picker defaults are cancelled, production permissions and settings are unchanged and the sidebar has no page errors');
 await writeFile('tmp/browser/gemini-upload-results.json',JSON.stringify({version:productionManifest.version,checks,errors,fileChoosers,browser:await context.browser().version(),bodyChars:body.length,fixtureOnly:true},null,2));console.log(JSON.stringify({passed:checks.length,errors}));
}catch(error){for(const page of context?.pages()||[]){if(!page.url().startsWith('chrome-extension:'))continue;for(const frame of page.frames().slice(1)){console.log('DEBUG '+(await frame.locator('body').innerText().catch(()=>'' )).slice(0,2500));console.log('STATUS '+JSON.stringify(await frame.locator('.status,.chip .excerpt').allTextContents().catch(()=>[])));console.log('NATIVE '+JSON.stringify(await frame.evaluate(()=>({disabled:document.querySelector('#send')?.disabled,uploads:uploads.length,removes,sent:sent.length})).catch(()=>({}))));}}throw error;}
finally{await context?.close();await new Promise(resolve=>tls.close(resolve));await new Promise(resolve=>source.close(resolve));}
